# Configuration Render pour deployment via Dockerfile
# Remplacez <YOUR_GIT_REPO> par <username>/<repo> ou l'URL appropri√©e
services:
  - type: web
    name: clinique-backend
    runtime: docker
    repo: https://github.com/dilane56/CLINIQUE-MANAGEMENT-BACKEND
    branch: main
    dockerfilePath: Dockerfile
    autoDeploy: true
    plan: starter
    # Optional: buildCommand si vous voulez forcer un build Maven explicite
    buildCommand: "./mvnw -B -DskipTests package"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: "8080"
    healthCheckPath: /actuator/health
